import Foundation
import Metal
import MetalPerformanceShadersGraph
import SwiftLM

/// Primitive MPSGraph operations for transformer inference.
///
/// Static functions that build MPSGraph tensor operations matching
/// the semantics of SwiftLM IR OperationKind primitives.
/// Used by `MPSGraphInferenceCompiler` during IR-to-MPSGraph compilation.
enum MPSGraphOps {

    // MARK: - Linear Projection

    /// x @ weight^T — standard linear projection.
    static func linear(
        _ graph: MPSGraph, input x: MPSGraphTensor, weight w: MPSGraphTensor, name: String
    ) -> MPSGraphTensor {
        graph.matrixMultiplication(
            primary: x,
            secondary: graph.transposeTensor(w, dimension: 0, withDimension: 1, name: nil),
            name: name)
    }

    // MARK: - RMSNorm

    /// RMSNorm: x * rsqrt(mean(x^2) + eps) * weight
    static func rmsNorm(
        _ graph: MPSGraph, input x: MPSGraphTensor, weight w: MPSGraphTensor,
        epsilon: Float, name: String
    ) -> MPSGraphTensor {
        let eps = graph.constant(Double(epsilon), dataType: .float16)
        let sq = graph.multiplication(x, x, name: "\(name).sq")
        let mean = graph.mean(of: sq, axes: [-1], name: "\(name).mean")
        let inv = graph.reverseSquareRoot(
            with: graph.addition(mean, eps, name: "\(name).eps"), name: "\(name).inv")
        let normed = graph.multiplication(x, inv, name: "\(name).normed")
        return graph.multiplication(normed, w, name: "\(name).out")
    }

    // MARK: - Multi-Head Reshape

    /// Reshape [B, T, heads*headDim] → [B, heads, T, headDim] for multi-head attention.
    static func toHeads(
        _ graph: MPSGraph, input x: MPSGraphTensor,
        heads: Int, headDim: Int, name: String
    ) -> MPSGraphTensor {
        let reshaped = graph.reshape(
            x, shape: [1, -1, heads as NSNumber, headDim as NSNumber], name: nil)
        return graph.transposeTensor(reshaped, dimension: 1, withDimension: 2, name: "\(name).heads")
    }

    /// Reshape [B, heads, T, headDim] → [B, T, heads*headDim] after attention.
    static func fromHeads(
        _ graph: MPSGraph, input x: MPSGraphTensor, totalDim: Int, name: String
    ) -> MPSGraphTensor {
        let transposed = graph.transposeTensor(x, dimension: 1, withDimension: 2, name: nil)
        return graph.reshape(transposed, shape: [1, -1, totalDim as NSNumber], name: "\(name).flat")
    }

    // MARK: - Scaled Dot-Product Attention with Causal Mask

    /// SDPA with optional additive mask: softmax((Q @ K^T / sqrt(d)) + mask) @ V
    ///
    /// The mask is an additive float16 tensor [1, 1, T, T] where masked positions
    /// contain -1e4 and valid positions contain 0. Pass `nil` for T=1 (no mask needed).
    /// The mask is generated by the caller (not inside the graph) to avoid
    /// MPSGraph MLIR compilation issues with dynamic coordinate ops.
    static func scaledDotProductAttention(
        _ graph: MPSGraph, query q: MPSGraphTensor, key k: MPSGraphTensor,
        value v: MPSGraphTensor, mask: MPSGraphTensor?, headDim: Int, name: String
    ) -> MPSGraphTensor {
        let scale = graph.constant(Double(1.0 / Float(headDim).squareRoot()), dataType: .float16)

        let kt = graph.transposeTensor(k, dimension: 2, withDimension: 3, name: nil)
        var scores = graph.multiplication(
            graph.matrixMultiplication(primary: q, secondary: kt, name: "\(name).qk"),
            scale, name: "\(name).scaled")

        if let mask {
            scores = graph.addition(scores, mask, name: "\(name).masked")
        }

        let weights = graph.softMax(with: scores, axis: -1, name: "\(name).sm")
        return graph.matrixMultiplication(primary: weights, secondary: v, name: "\(name).attn")
    }

    /// Build a causal mask as a Data blob for a given sequence length.
    /// Returns Float16 data of shape [1, 1, T, T] where future positions are -1e4.
    static func buildCausalMask(seqLen T: Int) -> Data {
        var mask = [Float16](repeating: 0, count: T * T)
        for i in 0..<T {
            for j in (i+1)..<T {
                mask[i * T + j] = Float16(-10000.0)
            }
        }
        return mask.withUnsafeBytes { Data($0) }
    }

    // MARK: - RoPE

    /// Apply Rotary Position Embedding using pre-computed cos/sin tables.
    ///
    /// cos/sin tables are passed as input tensors (not computed inside the graph)
    /// to avoid MPSGraph MLIR issues with dynamic coordinate ops.
    ///
    /// - Parameters:
    ///   - cosTable: [1, 1, T, hd/2] cos values for current positions
    ///   - sinTable: [1, 1, T, hd/2] sin values for current positions
    static func applyRoPE(
        _ graph: MPSGraph, input x: MPSGraphTensor,
        cosTable: MPSGraphTensor, sinTable: MPSGraphTensor,
        headDim: Int, name: String
    ) -> MPSGraphTensor {
        let halfDim = headDim / 2

        let xEven = graph.sliceTensor(x, dimension: 3, start: 0, length: halfDim, name: "\(name).xe")
        let xOdd = graph.sliceTensor(x, dimension: 3, start: halfDim, length: halfDim, name: "\(name).xo")

        let rotEven = graph.subtraction(
            graph.multiplication(xEven, cosTable, name: "\(name).ec"),
            graph.multiplication(xOdd, sinTable, name: "\(name).os"),
            name: "\(name).re")
        let rotOdd = graph.addition(
            graph.multiplication(xEven, sinTable, name: "\(name).es"),
            graph.multiplication(xOdd, cosTable, name: "\(name).oc"),
            name: "\(name).ro")

        return graph.concatTensors([rotEven, rotOdd], dimension: 3, name: "\(name).rope")
    }

    /// Build cos/sin tables for RoPE as Data blobs.
    ///
    /// Returns (cosData, sinData) each of shape [1, 1, T, hd/2] in Float16.
    ///
    /// - Parameters:
    ///   - seqLen: Number of positions to generate.
    ///   - headDim: Full head dimension (tables are hd/2 wide).
    ///   - theta: RoPE base frequency.
    ///   - scaling: Optional linear/yarn scaling that modifies frequencies.
    ///   - offset: Starting position index (for decode with cache offset).
    static func buildRoPETables(
        seqLen T: Int, headDim: Int, theta: Float,
        scaling: RoPEScaling? = nil, offset: Int = 0
    ) -> (cos: Data, sin: Data) {
        let halfDim = headDim / 2

        // Linear scaling: multiply frequencies by 1/factor
        let freqScale: Float
        switch scaling?.kind {
        case .linear: freqScale = 1.0 / scaling!.factor
        default: freqScale = 1.0
        }

        var cosValues = [Float16](repeating: 0, count: T * halfDim)
        var sinValues = [Float16](repeating: 0, count: T * halfDim)
        for pos in 0..<T {
            for i in 0..<halfDim {
                let freq = 1.0 / pow(theta, Float(2 * i) / Float(headDim))
                let angle = Float(pos + offset) * freq * freqScale
                cosValues[pos * halfDim + i] = Float16(cos(angle))
                sinValues[pos * halfDim + i] = Float16(sin(angle))
            }
        }
        return (cosValues.withUnsafeBytes { Data($0) },
                sinValues.withUnsafeBytes { Data($0) })
    }

    // MARK: - SiLU Gated MLP

    /// SiLU(gate) * up — gated activation for MLP.
    static func siluGate(
        _ graph: MPSGraph, gate: MPSGraphTensor, up: MPSGraphTensor, name: String
    ) -> MPSGraphTensor {
        let silu = graph.multiplication(
            gate, graph.sigmoid(with: gate, name: "\(name).sig"), name: "\(name).silu")
        return graph.multiplication(silu, up, name: "\(name).act")
    }

    // MARK: - GQA Head Repeat

    /// Tile K/V heads for GQA: [1, KVH, T, hd] → [1, H, T, hd]
    static func repeatKVHeads(
        _ graph: MPSGraph, input: MPSGraphTensor, repeatFactor: Int, name: String
    ) -> MPSGraphTensor {
        guard repeatFactor > 1 else { return input }
        return graph.tileTensor(
            input, withMultiplier: [1, repeatFactor, 1, 1] as [NSNumber], name: "\(name).rep")
    }
}
