@preconcurrency import MLX
import MLXNN
import SwiftLM

/// Lowered MLP (feed-forward network) with compile-time kernel selection.
///
/// Supports both gated (SwiGLU, GeGLU, GLU) and ungated architectures.
/// When gated and both projections share the same kernel variant,
/// gate+up are packed into a single matmul + split.
public struct LoweredMLP: @unchecked Sendable {

    /// Packed gate+up projection (single matmul + split).
    /// Non-nil when gating is enabled and packing succeeded at compile time.
    public let gateUpPacked: PackedProjection?

    /// Gate projection (fallback when packing is not possible or ungated).
    public let gateProj: LoweredProjection?

    /// Up projection for gated variants (fallback when packing is not possible).
    /// Nil when gating is `.none` or when packed.
    public let upProj: LoweredProjection?

    /// Down projection: `output = downProj(gated)`.
    public let downProj: LoweredProjection

    /// Activation function to apply to the gate projection output.
    public let activation: ActivationKind

    /// Fused activation+gate kernel — generated by MetalCodeGenerator from IR.
    /// Nil when gating is `.none` (no up projection to fuse with).
    private let fusedActivationKernel: FusedKernel?

    /// Initialize with packed gate+up projection.
    public init(
        gateUpPacked: PackedProjection,
        downProj: LoweredProjection,
        activation: ActivationKind
    ) {
        self.gateUpPacked = gateUpPacked
        self.gateProj = nil
        self.upProj = nil
        self.downProj = downProj
        self.activation = activation
        self.fusedActivationKernel = Self.buildFusedActivationKernel(
            activation: activation, hasUp: true)
    }

    /// Initialize with individual projections.
    public init(
        gateProj: LoweredProjection,
        downProj: LoweredProjection,
        upProj: LoweredProjection?,
        activation: ActivationKind
    ) {
        self.gateUpPacked = nil
        self.gateProj = gateProj
        self.upProj = upProj
        self.downProj = downProj
        self.activation = activation
        self.fusedActivationKernel = Self.buildFusedActivationKernel(
            activation: activation, hasUp: upProj != nil)
    }

    /// Generate fused activation+gate kernel from IR via MetalCodeGenerator.
    private static func buildFusedActivationKernel(
        activation: ActivationKind, hasUp: Bool
    ) -> FusedKernel? {
        guard hasUp else { return nil }

        let activationOp: MetalCodeGenerator.FusableOp
        switch activation {
        case .silu, .swish, .custom:
            activationOp = .silu(dst: "activated", src: "g")
        case .gelu:
            activationOp = .gelu(dst: "activated", src: "g")
        case .relu:
            activationOp = .relu(dst: "activated", src: "g")
        }

        let ops: [MetalCodeGenerator.FusableOp] = [
            .load(variable: "g", input: 0),
            .load(variable: "u", input: 1),
            activationOp,
            .multiply(dst: "out_val", lhs: "activated", rhs: "u"),
            .store(variable: "out_val", output: 0),
        ]

        let name: String
        switch activation {
        case .silu, .swish, .custom: name = "fused_silu_gate"
        case .gelu: name = "fused_gelu_gate"
        case .relu: name = "fused_relu_gate"
        }

        let kernel = FusedKernel(
            name: name,
            ops: ops,
            inputNames: ["gate", "up"],
            outputNames: ["out"]
        )
        print("[LMCompiler] fused kernel generated: \(name) (2 ops → 1 dispatch)")
        return kernel
    }

    /// Apply the MLP: `output = downProj(activation(gateProj(x)) * upProj(x))`.
    public func apply(_ x: MLXArray) -> MLXArray {
        let gate: MLXArray
        let up: MLXArray?

        if let gateUpPacked {
            let parts = gateUpPacked.apply(x)
            gate = parts[0]
            up = parts[1]
        } else {
            gate = gateProj!.apply(x)
            up = upProj?.apply(x)
        }

        let gated: MLXArray
        if let up, let fusedKernel = fusedActivationKernel {
            // IR-generated fused kernel: activation(gate) * up in 1 Metal dispatch
            let N = gate.shape.reduce(1, *)
            gated = fusedKernel.call(
                inputs: [gate.reshaped(-1), up.reshaped(-1)],
                gridSize: N,
                outputShapes: [gate.shape],
                dtype: gate.dtype
            )[0]
        } else if let up {
            // Fallback: separate ops (no fusion available)
            let activated: MLXArray
            switch activation {
            case .silu, .swish, .custom: activated = silu(gate)
            case .gelu: activated = gelu(gate)
            case .relu: activated = relu(gate)
            }
            gated = activated * up
        } else {
            switch activation {
            case .silu, .swish, .custom: gated = silu(gate)
            case .gelu: gated = gelu(gate)
            case .relu: gated = relu(gate)
            }
        }

        return downProj.apply(gated)
    }

    /// Apply MLP with residual add fused into downProj via addMM.
    /// `output = residual + downProj(activation(gate) * up)` — no separate add dispatch.
    public func applyWithResidual(_ x: MLXArray, residual: MLXArray) -> MLXArray {
        let gate: MLXArray
        let up: MLXArray?

        if let gateUpPacked {
            let parts = gateUpPacked.apply(x)
            gate = parts[0]
            up = parts[1]
        } else {
            gate = gateProj!.apply(x)
            up = upProj?.apply(x)
        }

        let gated: MLXArray
        if let up, let fusedKernel = fusedActivationKernel {
            let N = gate.shape.reduce(1, *)
            gated = fusedKernel.call(
                inputs: [gate.reshaped(-1), up.reshaped(-1)],
                gridSize: N,
                outputShapes: [gate.shape],
                dtype: gate.dtype
            )[0]
        } else if let up {
            let activated: MLXArray
            switch activation {
            case .silu, .swish, .custom: activated = silu(gate)
            case .gelu: activated = gelu(gate)
            case .relu: activated = relu(gate)
            }
            gated = activated * up
        } else {
            switch activation {
            case .silu, .swish, .custom: gated = silu(gate)
            case .gelu: gated = gelu(gate)
            case .relu: gated = relu(gate)
            }
        }

        // downProj + residual fused via addMM
        return downProj.applyWithResidual(gated, residual: residual)
    }
}
